Use full commit SHAs to satisfy changelog checks.
`maint-changelog-checks` was not happy about the short commits:

```
Traceback (most recent call last):
  File "/builds/gabi-250/arti/maint/gen_md_links", line 151, in <module>
    print(process(text))
          ^^^^^^^^^^^^^
  File "/builds/gabi-250/arti/maint/gen_md_links", line 134, in process
    return "".join(lnk.text() for lnk in items)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/gabi-250/arti/maint/gen_md_links", line 134, in <genexpr>
    return "".join(lnk.text() for lnk in items)
                   ^^^^^^^^^^
  File "/builds/gabi-250/arti/maint/gen_md_links", line 120, in text
    return "[{}]: {}\n".format(self._s, self.link())
                                        ^^^^^^^^^^^
  File "/builds/gabi-250/arti/maint/gen_md_links", line 114, in link
    full_id = lookup_git_commit(self._id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/gabi-250/arti/maint/gen_md_links", line 78, in lookup_git_commit
    raise ValueError(f"Unrecognized git commit {short}")
ValueError: Unrecognized git commit 04754e99
```