maint/check_doc_features: Include ; in end of item pattern.
This makes the script work on `cfg_attr`s applied to `mod` declarations
ending in `;`.

Without this change, the script fails with
```
processing tor-hsservice
    res += fn(os.path.join(dir_, file))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/nickm/arti/./maint/check_doc_features", line 112, in extract_cfg_attr
    end = min(subline.find(pat) for pat in ' (<' if subline.find(pat) !=-1)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: min() arg is an empty sequence
```

when run on code with `cfg_attr`s applied to `mod` declarations.

Note: this change just improves the UX a bit, but doesn't actually fix
the issue: the script still isn't able to handle `cfg_attr`'d `mod`s: it
assumes all `#[cfg_attr(docsrs, ..)]` statements are applied to
feature-gated `pub use`s, and if there aren't any (such as in the case
of `cfg_attr`d modules, it assumes the feature gating is missing.