CI: build-repro: Bump image to 1.63
tinystr 0.6.2 (which our Cargo.toml's permit and our Cargo.lock
specifies) has an MSRV of 1.60.

The symptom with earlier Rust is this from cargo:
   error: failed to select a version for the requirement `tinystr = "^0.6.0"`
(which is, on the face of it, nonsense).